sonarr:
  instance:
    base_url: http://sonarr:8989
    api_key: !secret SONARR_API_KEY
radarr:
  instance:
    base_url: http://radarr:7878
    api_key: !secret RADARR_API_KEY
bazarr:
  instance:
    base_url: http://bazarr:6767
    api_key: !secret BAZARR_API_KEY
